### ISSUE TITLE
老是卡在99%就不去了

### ISSUE THREAD

**Issue by lengyan6** [liyupi/daxigua#11]

**Comment by lengyan6** [comment]
上传源码到空间打开会卡在99%

**Comment by qeqeq1** [comment]
f12查看一下报错是什么，一般来说卡在99就是某个资源没有加载

**Comment by liyupi** [comment]
楼上同学说得对，可以阅读下 https://github.com/liyupi/daxigua#%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3
