### ISSUE TITLE
Docker运行+nginx转发会产生502Bad GateWay

### ISSUE THREAD

**Issue by KuangjuX** [liyupi/daxigua#12]
我尝试去使用docker对项目源码进行部署，我将容器运行在我的服务上并对docker暴露出的端口使用Nginx进行转发，会发生502 Bad Gateway。
具体的Dockerfile如下：
```
FROM node:8.15.1-alpine as build-stage

WORKDIR /app

COPY . .

EXPOSE 5000

CMD ["/bin/sh", "/app/script/build.sh"]
```
所执行的脚本如下：
```
#!/usr/bin/env bash
cd  /app/ \
    && npm i -g serve \
    && serve
```
以上为构建docker镜像的过程，然后使用`docker run -p 5000:5000 -d watermelon`去运行容器，访问暴露在外的网址时，却发生了502Bad GateWay? 请问这是怎么一回事？

**Comment by liyupi** [comment]
容器中有 npm 么

**Comment by liyupi** [comment]
看下5000端口是否成功启动了，感觉和路径有点关系，有同学贡献了一个dockerfile，可以试试~

**Comment by KuangjuX** [comment]
刚才使用提供的Dockerfile尝试了一下还是不行，于是遂把nginx代理转发的配置文件关了直接访问端口发现可行，发现应该是nginx配置文件写错了。谢谢鱼皮大大了。
