### ISSUE TITLE
请问发布的在线游戏在手机端是否可以运行吗？以及PC网页端的分辨率问题该如何解决？

### ISSUE THREAD

**Issue by SSZ1** [liyupi/daxigua#17]
在pc端运行游戏是这样的，
![image](https://user-images.githubusercontent.com/36888758/106576479-1d7acc80-6578-11eb-9aaa-3aeff31f9824.png)

在手机端进入网址https://dadaxigua.liyupi.com，就会卡在99%

**Comment by liyupi** [comment]
PC端按f12，开启移动设备模式，刷新页面。
或者新建一个html用iframe嵌套网页，自己设置宽高
