### ISSUE TITLE
能否让游戏适配电脑浏览器的分辨率

### ISSUE THREAD

**Issue by xiaoxianghuayu** [liyupi/daxigua#3]
您好, 我试图在电脑浏览器上运行该游戏, 但是分辨率一直无法调整, 程序会直接填充整个网页, 但是只有上半部分, 不太了解这个引擎, 请问有没有什么好办法.

**Comment by gyz0108** [comment]
我也也到了这种情况，有解决办法吗?

**Comment by aaronxing** [comment]
同问

**Comment by qeqeq1** [comment]
目前可以曲线救国，用f12修改页面大小 刷新

**Comment by liyupi** [comment]
理论上是可以的，还没研究

**Comment by honjun** [comment]
F12左上角手机模拟器，或者用iframe实现 如https://www.17sucai.com/pins/demo-show?id=21510

**Comment by GaoZiXuan0213** [comment]
iframe实现代码:
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    <iframe frameborder="1" src="http://127.0.0.1:8000/index.html" scrolling="auto" width="375px" height="575px"></iframe>
</body>
</html>
要新建一个html再丢进去，iframe跳转至127.0.0.1:8000/index.html页面

**Comment by liyupi** [comment]
楼上正解
