### ISSUE TITLE
'vercel' 不是内部或外部命令，也不是可运行的程序或批处理文件

### ISSUE THREAD

**Issue by SHANGHAICHAO** [liyupi/daxigua#5]
你好！
我看了你的教程用了vercel来部署
但是我用npm安装了vercel之后没有这个命令，我找了半天也没找到vercel.exe这个程序
应该怎么正确地使用vercel呢？

**Comment by liyupi** [comment]
npm i -g vercel，请核对命令是否正确。安装后，关闭cmd再重启试试

**Comment by SHANGHAICHAO** [comment]
> npm i -g vercel，请核对命令是否正确。安装后，关闭cmd再重启试试

搞定了，没有exe的后缀，文件名只是单纯的vercel
我把nodejs/node-global文件夹添加到环境变量里就可以了：）
简直飞快

**Comment by liyupi** [comment]
太棒啦！
