### ISSUE TITLE
安装Serve出现问题

### ISSUE THREAD

**Issue by SSZ1** [liyupi/daxigua#6]
`npm i -g serve
[..................] | fetchMetadata: sill resolveWithNewModule serve@11.3.2 checking installable status`

**Comment by SSZ1** [comment]
`npm i -g serve`
`[..................] | fetchMetadata: sill resolveWithNewModule serve@11.3.2 checking installable status`

**Comment by liyupi** [comment]
是卡住么？

**Comment by SSZ1** [comment]
> 是卡住么？

是的，卡在这个状态不动

**Comment by SSZ1** [comment]
> 是卡住么？

![image](https://user-images.githubusercontent.com/36888758/106350162-ba3a3180-630e-11eb-931b-755397f82dfa.png)

**Comment by SSZ1** [comment]
> 是卡住么？

这个状态是不是在安装了？

**Comment by liyupi** [comment]
网络原因，我整理下大家共同遇到的问题，一会儿回复你~ 可以加我微信 liyupi66 哈

**Comment by liyupi** [comment]
https://github.com/liyupi/daxigua#%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3
看下这个哈，有你遇到的问题~

**Comment by SSZ1** [comment]
> https://github.com/liyupi/daxigua#%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3
> 看下这个哈，有你遇到的问题~
谢谢！
